# Generated by Django 5.2.17 on 2026-09-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cards",
            name="card_type",
            field=models.CharField(
                choices=[("CREDIT", "credit"), ("DEBIT", "debit")],
                default="CREDIT",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cards",
            name="last_four_digit",
            field=models.CharField(default="0000", max_length=4),
            preserve_default=False,
        ),
    ]
