# Generated by Django 5.2.17 on 2026-09-29 16:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_adminlogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="cards",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("5000.00"), max_digits=10
            ),
        ),
    ]
