# Generated by Django 5.2.17 on 2026-09-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_cards_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
