services:

  mysql:
    image: mysql:8.0
    container_name: credit-card-mysql

    environment:
      MYSQL_DATABASE: credit_card_system
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DB_PASSWORD}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  django:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - DB_PASSWORD=${DB_PASSWORD}

    container_name: credit-card-django

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    depends_on:
      mysql:
        condition: service_healthy

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi

    container_name: credit-card-fastapi

    environment:
      - DB_PASSWORD=${DB_PASSWORD}

    ports:
      - "8001:8001"

    volumes:
      - .:/app

    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: